import { useState, useRef, useMemo, useCallback } from 'react';
import Icon from './components/Icon';
import SourcesCard from './components/SourcesCard';
import RequirementsCard from './components/RequirementsCard';
import PreviewCard from './components/PreviewCard';
import ArtifactsCard from './components/ArtifactsCard';
import ActionsCard from './components/ActionsCard';
import CodeGenPanel from './components/CodeGenPanel';
import UserStoryReviewPanel from './components/UserStoryReviewPanel';
import Loader from './components/Loader';
import AuthPage from './components/AuthPage';
import EditProfilePage from './components/EditProfilePage';
import { sources } from './data';
import { config } from './config';
import { extractRequirementsFromDocx, generateOpenApi, generatePostmanCollection, generateDataModels, generateSwaggerDocs, fetchAzureStories, fetchJiraStories, fetchConfluenceStories, readExcelColumns, extractRequirementsFromExcel } from './services/documentService';import type { AzureConfig, JiraConfig, ConfluenceConfig, ExcelColumnMapping } from './services/documentService';
import ExcelColumnMapModal from './components/ExcelColumnMapModal';
import type { ActivityItem, Requirement } from './types';
import { isAuthenticated, getUser, logout, authHeaders } from './services/authService';
import UserMenu from './components/UserMenu';

export default function App() {
  // ── Auth state — MUST be first, before any early return ───────────────────
  const [authed, setAuthed] = useState(isAuthenticated());
  const [showEditProfile, setShowEditProfile] = useState(false);
  const [showResetPassword, setShowResetPassword] = useState(false);

  // ── All other hooks — declared unconditionally (Rules of Hooks) ───────────
  const [selectedSourceIds, setSelectedSourceIds] = useState<string[]>(sources.map((s) => s.id));
  const [requirements, setRequirements] = useState<Requirement[]>([]);
  const [reviewingStory, setReviewingStory] = useState<Requirement | null>(null);
  const [viewingStory, setViewingStory] = useState<Requirement | null>(null);
  const [selectedRequirement, setSelectedRequirement] = useState<Requirement | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedSpec, setGeneratedSpec] = useState('');
  const [postmanCollection, setPostmanCollection] = useState('');
  const [isGeneratingPostman, setIsGeneratingPostman] = useState(false);
  const [dataModels, setDataModels] = useState('');
  const [isGeneratingDataModels, setIsGeneratingDataModels] = useState(false);
  const [swaggerDocs, setSwaggerDocs] = useState('');
  const [isGeneratingSwagger, setIsGeneratingSwagger] = useState(false);
  const [tab, setTab] = useState('Extracted');
  const [search, setSearch] = useState('');
  const [toast, setToast] = useState('Select and review a user story to begin');
  const [activity, setActivity] = useState<ActivityItem[]>([{ label: 'Generated by', value: 'API Designer Agent' }]);
  const [lastGeneratedAt, setLastGeneratedAt] = useState('—');
  const [uploading, setUploading] = useState(false);
  const [uploadingExcel, setUploadingExcel] = useState(false);
  const [excelPending, setExcelPending] = useState<{ file: File; columns: string[]; rows: Record<string, string>[] } | null>(null);
  const [connectingAzure, setConnectingAzure] = useState(false);
  const [connectingJira, setConnectingJira] = useState(false);
  const [connectingConfluence, setConnectingConfluence] = useState(false);
  const [rawText, setRawText] = useState('');
  const previewRef = useRef<HTMLDivElement>(null);

  // ── Auth gate — after ALL hooks ───────────────────────────────────────────
  if (!authed) {
    return <AuthPage onAuthenticated={() => setAuthed(true)} />;
  }

  const user = getUser();
  const handleLogout = () => { logout(); setAuthed(false); };

  const connectingSource = connectingAzure ? 'azure' : connectingJira ? 'jira' : connectingConfluence ? 'confluence' : null;

  const visibleRequirements = requirements.filter((req) =>
    `${req.id} ${req.title} ${req.desc}`.toLowerCase().includes(search.toLowerCase())
  );

  const mergeRequirements = useCallback((fetched: Requirement[]) => {
    setRequirements((cur) => {
      const ids = new Set(cur.map((r) => r.id));
      return [...cur, ...fetched.filter((r) => !ids.has(r.id))];
    });
  }, []);

  // ── Status toggle handler ─────────────────────────────────────────────────
  const handleStatusChange = useCallback((id: string, status: 'Draft' | 'Approved' | 'Rejected') => {
    setRequirements((cur) => cur.map((r) => r.id === id ? { ...r, status } : r));
    setSelectedRequirement((cur) => cur?.id === id ? { ...cur, status } : cur);
    setToast(`Requirement ${id} marked as ${status}`);
  }, []);

  const handleRequirementStatusChange = useCallback((id: string, status: 'Draft' | 'Approved' | 'Rejected') => {
    handleStatusChange(id, status);
    if (status === 'Approved') {
      setRequirements((cur) => {
        const req = cur.find((r) => r.id === id);
        if (req) setSelectedRequirement({ ...req, status: 'Approved' });
        return cur;
      });
    } else {
      setSelectedRequirement((cur) => cur?.id === id ? null : cur);
    }
  }, [handleStatusChange]);

  // ── Azure DevOps handler ──────────────────────────────────────────────────
  const handleConnectAzure = async (cfg: AzureConfig) => {
    setConnectingAzure(true);
    setToast('Fetching user stories from Azure DevOps…');
    try {
      const fetched = await fetchAzureStories(cfg);
      mergeRequirements(fetched);
      setSelectedSourceIds((cur) => cur.includes('azure') ? cur : [...cur, 'azure']);
      setToast(`Fetched ${fetched.length} user stories from Azure DevOps`);
      setActivity((cur) => [{ label: 'Azure DevOps', value: `${fetched.length} stories imported` }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Azure DevOps connection failed');
    } finally { setConnectingAzure(false); }
  };

  // ── Jira handler ──────────────────────────────────────────────────────────
  const handleConnectJira = async (cfg: JiraConfig) => {
    setConnectingJira(true);
    setToast('Fetching issues from Jira…');
    try {
      const fetched = await fetchJiraStories(cfg);
      mergeRequirements(fetched);
      setSelectedSourceIds((cur) => cur.includes('jira') ? cur : [...cur, 'jira']);
      setToast(`Fetched ${fetched.length} issues from Jira`);
      setActivity((cur) => [{ label: 'Jira', value: `${fetched.length} stories imported` }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Jira connection failed');
    } finally { setConnectingJira(false); }
  };

  // ── Confluence handler ────────────────────────────────────────────────────
  const handleConnectConfluence = async (cfg: ConfluenceConfig) => {
    setConnectingConfluence(true);
    setToast('Fetching pages from Confluence…');
    try {
      const fetched = await fetchConfluenceStories(cfg);
      mergeRequirements(fetched);
      setSelectedSourceIds((cur) => cur.includes('confluence') ? cur : [...cur, 'confluence']);
      setToast(`Fetched ${fetched.length} requirements from Confluence`);
      setActivity((cur) => [{ label: 'Confluence', value: `${fetched.length} pages imported` }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Confluence connection failed');
    } finally { setConnectingConfluence(false); }
  };

  // ── Excel handler ─────────────────────────────────────────────────────────
  const handleUploadExcel = async (file: File) => {
    setToast(`Reading columns from ${file.name}…`);
    try {
      const { columns, rows } = await readExcelColumns(file);
      setExcelPending({ file, columns, rows });
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Failed to read Excel file');
    }
  };

  const handleExcelMappingConfirm = async (mapping: ExcelColumnMapping) => {
    if (!excelPending) return;
    const { file, rows } = excelPending;
    setExcelPending(null);
    setUploadingExcel(true);
    setToast(`Extracting requirements from ${file.name}…`);
    try {
      const fetched = await extractRequirementsFromExcel(file, rows, mapping);
      mergeRequirements(fetched);
      setSelectedSourceIds((cur) => cur.includes('excel') ? cur : [...cur, 'excel']);
      setToast(`Extracted ${fetched.length} requirements from ${file.name}`);
      setActivity((cur) => [{ label: 'Excel', value: file.name }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Excel extraction failed');
    } finally { setUploadingExcel(false); }
  };

  // ── Upload handler ────────────────────────────────────────────────────────
  const handleUploadDocx = async (file: File) => {
    setUploading(true);
    setToast('Extracting requirements from document…');
    try {
      const extracted = await extractRequirementsFromDocx(file);
      setRawText(extracted.rawText);
      mergeRequirements(extracted.requirements);
      setToast(`Extracted ${extracted.requirements.length} requirements from ${file.name}`);
      setActivity((cur) => [{ label: 'Uploaded', value: file.name }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Upload failed');
    } finally { setUploading(false); }
  };

  // ── Review panel confirm ──────────────────────────────────────────────────
  const handleConfirm = (story: Requirement) => {
    const approved: Requirement = { ...story, status: 'Approved' };
    setRequirements((cur) => cur.map((r) => r.id === approved.id ? approved : r));
    setSelectedRequirement(approved);
    setReviewingStory(null);
    setGeneratedSpec('');
    setToast(`Story ${approved.id} approved — ready to generate`);
    setActivity((cur) => [{ label: 'Approved', value: `${approved.id}: ${approved.title}` }, ...cur.slice(0, 2)]);
  };

  // ── Generate OpenAPI ──────────────────────────────────────────────────────
  const handleGenerate = async () => {
    if (!selectedRequirement || selectedRequirement.status !== 'Approved') {
      setToast('No approved requirement selected. Approve a requirement first.');
      return;
    }
    setIsGenerating(true);
    setGeneratedSpec('');
    setToast(`Generating OpenAPI for ${selectedRequirement.id}…`);
    try {
      const result = await generateOpenApi(selectedRequirement);
      const now = new Date().toLocaleString([], { dateStyle: 'medium', timeStyle: 'short' });
      setGeneratedSpec(result.yaml);
      setPostmanCollection('');
      setDataModels('');
      setSwaggerDocs('');
      setLastGeneratedAt(now);
      setToast(`OpenAPI spec generated for ${selectedRequirement.id}`);
      setActivity((cur) => [{ label: 'Generated', value: `${selectedRequirement.id}: ${selectedRequirement.title}` }, ...cur.slice(0, 2)]);
      if (window.innerWidth <= 1250) {
        previewRef.current?.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Generation failed');
    } finally { setIsGenerating(false); }
  };

  // ── Generate Postman Collection ───────────────────────────────────────────
  const handleGeneratePostman = async () => {
    if (!generatedSpec || !selectedRequirement) return;
    setIsGeneratingPostman(true);
    setToast('Generating Postman collection…');
    try {
      const collection = await generatePostmanCollection(generatedSpec, selectedRequirement.title);
      setPostmanCollection(collection);
      setToast('Postman collection ready');
      setActivity((cur) => [{ label: 'Postman', value: `${selectedRequirement.id}: ${selectedRequirement.title}` }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Postman generation failed');
    } finally { setIsGeneratingPostman(false); }
  };

  // ── Generate Swagger Docs ─────────────────────────────────────────────────
  const handleGenerateSwagger = async () => {
    if (!generatedSpec || !selectedRequirement) return;
    setIsGeneratingSwagger(true);
    setToast('Generating Swagger docs…');
    try {
      const html = await generateSwaggerDocs(generatedSpec);
      setSwaggerDocs(html);
      setToast('Swagger docs ready');
      setActivity((cur) => [{ label: 'Swagger', value: `${selectedRequirement.id}: ${selectedRequirement.title}` }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Swagger generation failed');
    } finally { setIsGeneratingSwagger(false); }
  };

  // ── Generate Data Models ──────────────────────────────────────────────────
  const handleGenerateDataModels = async () => {
    if (!generatedSpec || !selectedRequirement) return;
    setIsGeneratingDataModels(true);
    setToast('Generating data models…');
    try {
      const models = await generateDataModels(generatedSpec);
      setDataModels(models);
      setToast('Data models ready');
      setActivity((cur) => [{ label: 'Data Models', value: `${selectedRequirement.id}: ${selectedRequirement.title}` }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Data model generation failed');
    } finally { setIsGeneratingDataModels(false); }
  };

  // ── Misc handlers ─────────────────────────────────────────────────────────
  const toggleSource = (id: string) => {
    setSelectedSourceIds((cur) => cur.includes(id) ? cur.filter((i) => i !== id) : [...cur, id]);
    setToast('Source selection updated');
  };

  const downloadFile = (filename: string, contents: string, type = 'text/plain') => {
    const blob = new Blob([contents], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
    setToast(`${filename} prepared for download`);
  };

  const runAction = (name: string) => {
    const messages: Record<string, string> = {
      'Generate / Regenerate': selectedRequirement ? `Regenerated design for ${selectedRequirement.id}` : 'Approve a story first',
      'Validate OpenAPI Spec': 'Validation passed: 0 errors, 2 warnings',
      'Export to API Gateway': 'Export package queued for Kong, Apigee, and Azure APIM',
      'Compare Changes': 'Compared against v1.3: 2 endpoints changed',
      'Version History': 'Loaded 6 generated versions',
    };
    if (name === 'Generate / Regenerate') { handleGenerate(); return; }
    setToast(messages[name]);
    setActivity((cur) => [{ label: 'Action', value: name }, ...cur.slice(0, 2)]);
  };

  return (
    <main>
      <header className="top-header">
        <div className="logo-box"><Icon name="logo" size={34} /></div>
        <div className="header-title">
          <h1>API Designer Agent <span>L4 - AUTONOMOUS</span></h1>
          <p>Generates OpenAPI specifications and API design artifacts from functional requirements.</p>
        </div>
        <div className="header-pills">
          <button onClick={() => setToast('AI design assistance is enabled')}><Icon name="spark" />AI Powered</button>
          <button onClick={() => setToast('Connector marketplace opened')}><Icon name="plug" />Plug &amp; Play</button>
          <button onClick={() => setToast('Cloud, on-prem, and hybrid targets supported')}><Icon name="globe" />Cross Platform</button>
          {user && (
            <UserMenu
              user={user}
              onProfile={() => setShowEditProfile(true)}
              onResetPassword={() => setShowResetPassword(true)}
              onLogout={handleLogout}
            />
          )}
        </div>
      </header>

      <section className="columns-wrapper">
        <SourcesCard
          selectedSourceIds={selectedSourceIds}
          onToggle={toggleSource}
          onAddSource={() => setToast('Add connector flow opened')}
          onSync={() => setToast('Sources synced just now')}
          onUploadDocx={handleUploadDocx}
          uploading={uploading}
          onConnectAzure={handleConnectAzure}
          onConnectJira={handleConnectJira}
          onConnectConfluence={handleConnectConfluence}
          connectingSource={connectingSource}
          onUploadExcel={handleUploadExcel}
          uploadingExcel={uploadingExcel}
        />

        <div className="arrow-col"><Icon name="arrow" size={24} /></div>

        <RequirementsCard
          requirements={visibleRequirements}
          selectedRequirement={selectedRequirement}
          rawText={rawText}
          search={search}
          tab={tab}
          onTabChange={setTab}
          onSearchChange={setSearch}
          onSelectRequirement={(req) => setReviewingStory(req)}
          onViewRequirement={(req) => setViewingStory(req)}
          onStatusChange={handleRequirementStatusChange}
          onGenerate={handleGenerate}
          isGenerating={isGenerating}
          onFilter={() => setToast('Filtered high-confidence requirements')}
          onRefresh={() => setToast('Requirements refreshed')}
        />

        <div className="arrow-col"><Icon name="arrow" size={24} /></div>

        <div ref={previewRef}>
          <PreviewCard
            spec={generatedSpec}
            toast={toast}
            lastGeneratedAt={lastGeneratedAt}
            isGenerating={isGenerating}
            onPreview={() => setToast('Preview rendered in YAML mode')}
            onDownload={() => downloadFile('openapi.yaml', generatedSpec, 'application/yaml')}
            onDownloadJson={async () => {
              try {
                const res = await fetch(`${config.apiBaseUrl}/api/designer/artifact`, {
                  method: 'POST',
                  headers: { 'Content-Type': 'application/json', ...authHeaders() },
                  body: JSON.stringify({ open_api_yaml: generatedSpec, artifact_type: 'json' }),
                });
                if (res.status === 401) { logout(); window.location.reload(); return; }
                const data = await res.json();
                downloadFile('openapi.json', data.content, 'application/json');
              } catch { setToast('Failed to convert to JSON'); }
            }}
          />
        </div>

        <div className="arrow-col"><Icon name="arrow" size={24} /></div>

        <ArtifactsCard
          selectedRequirement={selectedRequirement}
          generatedSpec={generatedSpec}
          postmanCollection={postmanCollection}
          isGeneratingPostman={isGeneratingPostman}
          dataModels={dataModels}
          isGeneratingDataModels={isGeneratingDataModels}
          swaggerDocs={swaggerDocs}
          isGeneratingSwagger={isGeneratingSwagger}
          lastGeneratedAt={lastGeneratedAt}
          activity={activity}
          onDownload={downloadFile}
          onGeneratePostman={handleGeneratePostman}
          onGenerateDataModels={handleGenerateDataModels}
          onGenerateSwagger={handleGenerateSwagger}
        />
      </section>

      {/* <section className="bottom-grid">
        <ActionsCard onAction={runAction} />
      </section> */}

      <CodeGenPanel
        openApiYaml={generatedSpec}
        projectName={selectedRequirement?.title?.replace(/\s+/g, '') ?? 'GeneratedApi'}
      />


      <UserStoryReviewPanel
        story={reviewingStory}
        onClose={() => setReviewingStory(null)}
        onConfirm={handleConfirm}
      />

      <UserStoryReviewPanel
        story={viewingStory}
        onClose={() => setViewingStory(null)}
        onConfirm={handleConfirm}
        viewOnly
      />

      {excelPending && (
        <ExcelColumnMapModal
          columns={excelPending.columns}
          filename={excelPending.file.name}
          onConfirm={handleExcelMappingConfirm}
          onCancel={() => setExcelPending(null)}
        />
      )}
      {uploading && <Loader message="Extracting requirements from document…" />}
      {showEditProfile && <EditProfilePage onClose={() => setShowEditProfile(false)} view="profile" />}
      {showResetPassword && <EditProfilePage onClose={() => setShowResetPassword(false)} view="reset-password" />}
      {uploadingExcel && <Loader message="Extracting requirements from spreadsheet…" />}
      {connectingAzure && <Loader message="Fetching stories from Azure DevOps…" />}
      {connectingJira && <Loader message="Fetching issues from Jira…" />}
      {connectingConfluence && <Loader message="Fetching pages from Confluence…" />}
      {isGenerating && <Loader message="Generating OpenAPI specification…" />}
    </main>
  );
}
