import { useState } from 'react';
import Icon from './components/Icon';
import SourcesCard from './components/SourcesCard';
import RequirementsCard from './components/RequirementsCard';
import PreviewCard from './components/PreviewCard';
import ArtifactsCard from './components/ArtifactsCard';
import ActionsCard from './components/ActionsCard';
import FeaturesCard from './components/FeaturesCard';
import UserStoryReviewPanel from './components/UserStoryReviewPanel';
import { sources } from './data';
import { extractRequirementsFromDocx, generateOpenApi } from './services/documentService';
import type { ActivityItem, Requirement } from './types';

export default function App() {
  const [selectedSourceIds, setSelectedSourceIds] = useState<string[]>(sources.map((s) => s.id));
  const [requirements, setRequirements] = useState<Requirement[]>([]);

  // Review flow state
  const [reviewingStory, setReviewingStory] = useState<Requirement | null>(null);
  const [confirmedStory, setConfirmedStory] = useState<Requirement | null>(null);

  // Generation state
  const [isGenerating, setIsGenerating] = useState(false);
  const [generatedSpec, setGeneratedSpec] = useState('');

  const [tab, setTab] = useState('Extracted');
  const [search, setSearch] = useState('');
  const [toast, setToast] = useState('Select and review a user story to begin');
  const [activity, setActivity] = useState<ActivityItem[]>([{ label: 'Generated by', value: 'API Designer Agent' }]);
  const [lastGeneratedAt, setLastGeneratedAt] = useState('—');
  const [uploading, setUploading] = useState(false);

  const selectedRequirement = confirmedStory;

  const visibleRequirements = requirements.filter((req) =>
    `${req.id} ${req.title} ${req.desc}`.toLowerCase().includes(search.toLowerCase())
  );

  // ── Status toggle handler ───────────────────────────────────────────────────
  const handleStatusChange = (id: string, status: 'Draft' | 'Approved' | 'Rejected') => {
    setRequirements((cur) => cur.map((r) => r.id === id ? { ...r, status } : r));
    if (confirmedStory?.id === id) {
      setConfirmedStory((cur) => cur ? { ...cur, status } : cur);
    }
    setToast(`Requirement ${id} marked as ${status}`);
  };

  // ── Upload handler ──────────────────────────────────────────────────────────
  const handleUploadDocx = async (file: File) => {
    setUploading(true);
    setToast('Extracting requirements from document…');
    try {
      const extracted = await extractRequirementsFromDocx(file);
      setRequirements((cur) => {
        const existingIds = new Set(cur.map((r) => r.id));
        return [...cur, ...extracted.filter((r) => !existingIds.has(r.id))];
      });
      setToast(`Extracted ${extracted.length} requirements from ${file.name}`);
      setActivity((cur) => [{ label: 'Uploaded', value: file.name }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Upload failed');
    } finally {
      setUploading(false);
    }
  };

  // ── Generate OpenAPI via backend ────────────────────────────────────────────
  const handleGenerate = async () => {
    if (!selectedRequirement) {
      setToast('No approved requirement selected. Approve a requirement first.');
      return;
    }
    setIsGenerating(true);
    setGeneratedSpec('');
    setToast(`Generating OpenAPI for ${selectedRequirement.id}…`);
    try {
      const result = await generateOpenApi(selectedRequirement);
      const now = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit', second: '2-digit' });
      setGeneratedSpec(result.yaml);
      setLastGeneratedAt(now);
      setToast(`OpenAPI spec generated for ${selectedRequirement.id}`);
      setActivity((cur) => [{ label: 'Generated', value: `${selectedRequirement.id}: ${selectedRequirement.title}` }, ...cur.slice(0, 2)]);
    } catch (err: unknown) {
      setToast(err instanceof Error ? err.message : 'Generation failed');
    } finally {
      setIsGenerating(false);
    }
  };

  // ── Misc handlers ───────────────────────────────────────────────────────────
  const toggleSource = (id: string) => {
    setSelectedSourceIds((cur) => cur.includes(id) ? cur.filter((i) => i !== id) : [...cur, id]);
    setToast('Source selection updated');
  };

  const downloadFile = (filename: string, contents: string, type = 'text/plain') => {
    const blob = new Blob([contents], { type });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
    setToast(`${filename} prepared for download`);
  };

  const runAction = (name: string) => {
    const messages: Record<string, string> = {
      'Generate / Regenerate': confirmedStory ? `Regenerated design for ${confirmedStory.id}` : 'Approve a story first',
      'Validate OpenAPI Spec': 'Validation passed: 0 errors, 2 warnings',
      'Export to API Gateway': 'Export package queued for Kong, Apigee, and Azure APIM',
      'Compare Changes': 'Compared against v1.3: 2 endpoints changed',
      'Version History': 'Loaded 6 generated versions'
    };
    if (name === 'Generate / Regenerate') {
      handleGenerate();
      return;
    }
    setToast(messages[name]);
    setActivity((cur) => [{ label: 'Action', value: name }, ...cur.slice(0, 2)]);
  };

  return (
    <main>
      <header className="top-header">
        <div className="logo-box"><Icon name="logo" size={34} /></div>
        <div className="header-title">
          <h1>API Designer Agent <span>L4 - AUTONOMOUS</span></h1>
          <p>Generates OpenAPI specifications and API design artifacts from functional requirements.</p>
        </div>
        <div className="header-pills">
          <button onClick={() => setToast('AI design assistance is enabled')}><Icon name="spark" />AI Powered</button>
          <button onClick={() => setToast('Connector marketplace opened')}><Icon name="plug" />Plug &amp; Play</button>
          <button onClick={() => setToast('Cloud, on-prem, and hybrid targets supported')}><Icon name="globe" />Cross Platform</button>
        </div>
      </header>

      <section className="columns-wrapper">
        <SourcesCard
          selectedSourceIds={selectedSourceIds}
          onToggle={toggleSource}
          onAddSource={() => setToast('Add connector flow opened')}
          onSync={() => setToast('Sources synced just now')}
          onUploadDocx={handleUploadDocx}
          uploading={uploading}
        />

        <div className="arrow-col"><Icon name="arrow" size={24} /></div>

        <RequirementsCard
          requirements={visibleRequirements}
          selectedRequirement={selectedRequirement}
          search={search}
          tab={tab}
          onTabChange={setTab}
          onSearchChange={setSearch}
          onSelectRequirement={(req) => setReviewingStory(req)}
          onStatusChange={handleStatusChange}
          onGenerate={handleGenerate}
          onFilter={() => setToast('Filtered high-confidence requirements')}
          onRefresh={() => setToast('Requirements refreshed')}
        />

        <div className="arrow-col"><Icon name="arrow" size={24} /></div>

        <PreviewCard
          spec={generatedSpec}
          toast={toast}
          lastGeneratedAt={lastGeneratedAt}
          isGenerating={isGenerating}
          onPreview={() => setToast('Preview rendered in YAML mode')}
          onDownload={() => downloadFile('openapi.yaml', generatedSpec, 'application/yaml')}
        />

        <div className="arrow-col"><Icon name="arrow" size={24} /></div>

        <ArtifactsCard
          selectedRequirement={selectedRequirement}
          lastGeneratedAt={lastGeneratedAt}
          activity={activity}
          onDownload={downloadFile}
        />
      </section>

      <section className="bottom-grid">
        <ActionsCard onAction={runAction} />
        <FeaturesCard />
      </section>

      <footer>
        <Icon name="plug" />
        <strong>Plug &amp; Play</strong>
        <span>Works on any platform (Cloud / On-Prem / Hybrid)</span>
        <span>Integrates with your tools and processes</span>
        <span>Accelerate API design by 70%+</span>
      </footer>

      <UserStoryReviewPanel
        story={reviewingStory}
        onClose={() => setReviewingStory(null)}
        onConfirm={(story) => {
          const approved: Requirement = { ...story, status: 'Approved' };
          setRequirements((cur) => cur.map((r) => r.id === approved.id ? approved : r));
          setConfirmedStory(approved);
          setReviewingStory(null);
          setGeneratedSpec('');
          setToast(`Story ${approved.id} approved — ready to generate`);
          setActivity((cur) => [{ label: 'Approved', value: `${approved.id}: ${approved.title}` }, ...cur.slice(0, 2)]);
        }}
      />
    </main>
  );
}
